### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by zakhar-push** [zakhar-push/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by zakharcollaborator** [comment]
LANGUAGES
English Spanish Chinese Penguin Drunk

SKILLS
-	talented fighter (fighting with great prowess in his duel with Peter Griffin)
-	fluent in more than six languages
-	able to motivate people for just causes, such as shutting down the nuclear plant
-	play the guitar amazingly well, play the piano like a natural, and became an accomplished singer and songwriter
-	once was a very talented gymnast 

CHARACTER
“Relax, what is mind, no matter, what is matter, never mind”
“Better them than me...Oh wait, that was me.”

LIKES
dancing, eating donuts, drinking beer, hugging, driving an arcade sitdown racer, playing the piano, riding a horse, hi-5, spending time with my family.  Also I like "Stuart Little", "Barney Train", and "Ride the Champion Mechanical Horse".

DISLIKES
Working on Mr. Burns, Patty and Selma, Flanders

WANTS
Whatever, I'll be at Moe's
