### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by zakhar-push** [zakhar-push/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by zakharcollaborator** [comment]
1985
Springfield High School, Springfield, USA 			
High school prep diploma

1990 to 1990
Springfield Isotopes Baseball Club, Springfield, USA 					 
Game Mascot 
-	Generated 25% increase in fan interest and 50% jump in beer sales by leading cheers at home games for minor league baseball team.

1992 to 1993
Mr. Plow, Springfield, USA								 
Owner, Chief Marketing Officer, and Chief Driver for Snow-Plowing Business 
-	Boosted business 15% by executing late-night TV marketing campaign targeting homeowners who were too wasted to shovel their driveways. 
-	Deliberated at length before rescuing man trapped beneath mountain avalanche.

1994 to 1994
National Aeronautics and Space Administration (NASA), Cape Canaveral, FL 		 
Astronaut 
-	Averted in-flight disaster by forcing giant ants out of cockpit during space shuttle mission

1994 to 1996
Springfield Plumbing&Heating 							
Plumber’s Assistant Springfield, OR
-	Operated equipment drilling holes for installation, cutting piping, and testing completed plumbing
-	Organized tools, piping, and fittings to ensure smooth work-flow on the job-site
-	Aided in plumbing 30+ new-construction houses without damage
-	Assisted in increasing the amount of time needed to plumb an entire 1.5 bathroom house by >30%

1996 to 1997
Pizza Planet 										
Delivery Driver Springfield, OR
-	Developed strong multitasking skills assisting in the restaurant while keeping track of upcoming deliveries
-	Maintained high standards of customer service in a fast-paced environment
-	Collaborated with delivery team grouping orders to optimize routes for efficiency and to meet expectations
-	Trained 5+ delivery drivers how to steal gasoline
-	Mentored delivery team further on developing good habits and handling challenging situations
-	Has eaten more XL pizzas than this restaurant has sold and assisted in winning a district-wide competition

1997 to 1998
Moe's Tavern and Homer's Hunting Club, Springfield, USA 				 
Bartender 
-	Engaged patrons in witty, whimsical, avuncular dialog covering topics such as the arts, philosophy, politics, and spectator sports. 
-	Launched remodeling project that led to 100% reduction in clientele (including myself).

1998 to 1998
City of Springfield, Springfield, USA 							 
Chief of Police 
-	Broke up weasel-selling ring. 
-	Secured community support in almost-successful effort to expel organized crime from city.

1998 to present
Springfield Nuclear Power Plant, Springfield, USA 					 
Safety Inspector 
-	Strengthened safety procedures that resulted in 75% fewer accidents on days I was absent. 
-	Pioneered workplace stress-reduction methods that worked for at least one employee.
-	Collect and prepare radiologically contaminated material for removal
-	Follow all Nuclear Regulatory Commission regulations and site procedures

2000
Montgomery Burns Award for Outstanding Service in the Field of Excellence
