### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by zakhar-push** [zakhar-push/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by zakharcollaborator** [comment]
D'oh! I need to find a job. I`m lazy, and often ignorant to the world around me I spend a great deal of my time at Moe's Tavern  with my lifelong friends Barney, Carl, Lenny, and the bartender Moe. I can often be found sitting on the couch mindlessly watching TV while snacking on food and drinking beer Duff. My favorite color is blue, and I enjoy dancing, eating donuts…is that a box of donuts?? Mmmmmm DOOOnuts!
